### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by romagnolid** [Sage-Bionetworks/synapser#156]
## Operating system

Ubuntu Linux 16.04

### Actual behavior

```
rc = pip.main(['install', packageName,  '--upgrade', '--quiet', '--target', target])
AttributeError
: 
module 'pip' has no attribute 'main'
```
## Pip version
    pip 10.0.1 (python 3.5)

## Output of `sessionInfo()`

```
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 os       Ubuntu 16.04.3 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/San_Marino           
 date     2018-04-23                  

─ Packages ───────────────────────────────────────────────────────────────────
 package       * version     date       source                            
 assertthat      0.2.0       2017-04-11 CRAN (R 3.4.3)                    
 backports       1.1.2       2017-12-13 CRAN (R 3.4.3)                    
 BiocInstaller * 1.28.0      2018-02-09 Bioconductor                      
 callr           2.0.2.9002  2018-04-05 Github (r-lib/callr@9c38827)      
 cli             1.0.0       2017-11-05 cran (@1.0.0)                     
 clisymbols      1.2.0       2017-05-21 cran (@1.2.0)                     
 colorout      * 1.2-0       2018-02-15 Github (jalvesaq/colorout@2fd35ab)
 crayon          1.3.4       2017-09-16 cran (@1.3.4)                     
 debugme         1.1.0       2017-10-22 cran (@1.1.0)                     
 desc            1.1.1       2017-08-03 CRAN (R 3.4.3)                    
 devtools      * 1.13.5.9000 2018-04-05 Github (r-lib/devtools@5a1b9d9)   
 digest          0.6.15      2018-01-28 CRAN (R 3.4.3)                    
 magrittr        1.5         2014-11-22 cran (@1.5)                       
 memoise         1.1.0       2017-04-21 CRAN (R 3.4.3)                    
 pkgbuild        1.0.0       2018-04-05 Github (r-lib/pkgbuild@015f7f6)   
 pkgload         1.0.0       2018-04-05 Github (r-lib/pkgload@bd40696)    
 R6              2.2.2       2017-06-17 CRAN (R 3.4.3)                    
 rlang           0.2.0       2018-02-20 cran (@0.2.0)                     
 rprojroot       1.3-2       2018-01-03 CRAN (R 3.4.3)                    
 sessioninfo     1.0.0       2017-06-21 cran (@1.0.0)                     
 testthat        2.0.0       2017-12-13 CRAN (R 3.4.3)                    
 usethis       * 1.3.0       2018-02-24 cran (@1.3.0)                     
 withr           2.1.2       2018-03-15 cran (@2.1.2)          
```

**Comment by kimyen** [comment]
Hello @romagnolid,
Thank you for reporting the issue, and give us detailed information! Could you provide the detailed error, including the command that you used to install the package and the error output?

**Comment by romagnolid** [comment]
```
> install.packages("synapser", repos=c("https://sage-bionetworks.github.io/ran", "http://cran.fhcrc.org"))
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://sage-bionetworks.github.io/ran/src/contrib/synapser_0.1.28.tar.gz'
Content type 'application/gzip' length 111269 bytes (108 KB)
==================================================
downloaded 108 KB

* installing *source* package ‘synapser’ ...
Loading required package: R6
Loading required package: R6


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/RtmprfMEbk/R.INSTALL142e63cd6ba45/synapser/inst/python/installPythonClient.py", line 56, in main

    
stdouterrCapture(lambda: call_pip('pandas', localSitePackages), abbreviateStackTrace=False)
  File "/tmp/RtmprfMEbk/R.INSTALL142e63cd6ba45/synapser/inst/python/stdouterrCapture.py", line 45, in stdouterrCapture

    
raise exceptionToRaise
  File "/tmp/RtmprfMEbk/R.INSTALL142e63cd6ba45/synapser/inst/python/stdouterrCapture.py", line 21, in stdouterrCapture

    
return function()
  File "/tmp/RtmprfMEbk/R.INSTALL142e63cd6ba45/synapser/inst/python/installPythonClient.py", line 56, in <lambda>

    
stdouterrCapture(lambda: call_pip('pandas', localSitePackages), abbreviateStackTrace=False)
  File "/tmp/RtmprfMEbk/R.INSTALL142e63cd6ba45/synapser/inst/python/installPythonClient.py", line 105, in call_pip

    
rc = pip.main(['install', packageName,  '--upgrade', '--quiet', '--target', target])
AttributeError
: 
module 'pip' has no attribute 'main'
Error in pyExec(command) : 
  An error has occurred while executing Python code. See traceback above.
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/lib/R/site-library/synapser’

The downloaded source packages are in
        ‘/tmp/RtmplOhwmG/downloaded_packages’
Warning message:
In install.packages("synapser", repos = c("https://sage-bionetworks.github.io/ran",  :
  installation of package ‘synapser’ had non-zero exit status
> 
```
After my patch (https://github.com/romagnolid/synapser/commit/8b0ab64f55008cf497102613e51462e3b84cc709)
another error occures:
```
> install_github("romagnolid/synapser", ref="fix-issue-156")
Downloading GitHub repo romagnolid/synapser@fix-issue-156
from URL https://api.github.com/repos/romagnolid/synapser/zipball/fix-issue-156
Installing synapser
Running /usr/lib/R/bin/R CMD INSTALL \
  /tmp/RtmplOhwmG/devtools14231bc676ec/romagnolid-synapser-8b0ab64 \
  '--library=/usr/local/lib/R/site-library' --install-tests 
* installing *source* package ‘synapser’ ...
Loading required package: R6
Loading required package: R6

**synapseclient 1.7.5 requires requests>=1.2, which is not installed.**
```
[...]
```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/RtmplOhwmG/devtools14231bc676ec/romagnolid-synapser-8b0ab64/inst/python/installPythonClient.py", line 87, in main

    
import synapseclient
  File "/tmp/RtmplOhwmG/devtools14231bc676ec/romagnolid-synapser-8b0ab64/inst/lib/python3.5/site-packages/synapseclient-1.7.5-py3.5.egg/synapseclient/__init__.py", line 308, in <mo
dule>

    
from .client import Synapse, login
  File "/tmp/RtmplOhwmG/devtools14231bc676ec/romagnolid-synapser-8b0ab64/inst/lib/python3.5/site-packages/synapseclient-1.7.5-py3.5.egg/synapseclient/client.py", line 76, in <modul
e>

    
from . import cache
  File "/tmp/RtmplOhwmG/devtools14231bc676ec/romagnolid-synapser-8b0ab64/inst/lib/python3.5/site-packages/synapseclient-1.7.5-py3.5.egg/synapseclient/cache.py", line 28, in <module
>

    
import synapseclient.utils as utils
  File "/tmp/RtmplOhwmG/devtools14231bc676ec/romagnolid-synapser-8b0ab64/inst/lib/python3.5/site-packages/synapseclient-1.7.5-py3.5.egg/synapseclient/utils.py", line 13, in <module
>

    
from future.utils import implements_iterator
ImportError
: 
No module named 'future'
Error in pyExec(command) : 
  An error has occurred while executing Python code. See traceback above.
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/lib/R/site-library/synapser’
Installation failed: run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),      stderr_line_callback = real_callback(stderr), stdout_callback = real_block_cal
lback,      stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error
```
Note that **requests** is installed.
I think that's an issue related to pip https://github.com/pypa/pip/issues/5221

**Comment by kimyen** [comment]
Hi @romagnolid ,

In synapser, we separate the Python search path from user's Python environment. Therefore, user's installed pip would not effect synapser's pip version. 

When you give us information about the pip version (on your first comment), do you refer to the user's installed pip, or the one that comes with synapser?

**Comment by romagnolid** [comment]
I referred to the user's version.
Il ven 27 apr 2018, 02:55 Kimyen <notifications@github.com> ha scritto:

**Comment by romagnolid** [comment]
Hi @kimyen, I  removed PythonEmbedInR and tried to install synapser again but without success, the error persists.

**Comment by romagnolid** [comment]
@kimyen sorry, I've been a little to concise in my previous message.
Indeed PythonEmbedInR was installed successfully. Here are all the ouputs you required.

1. I followed the README instruction to install from RAN

```
install.packages("synapser", repos=c("https://sage-bionetworks.github.io/ran", "http://cran.fhcrc.org"))
```

2.  From devtools::session_info()
```
package        * version     date       source
PythonEmbedInR * 0.2.21      2018-05-09 local 
```
3.
```
> library(PythonEmbedInR)
Loading required package: R6
Loading required package: rjson
> pyImport("pip")
> pyPrint("pip.__version__")
10.0.1
```

4.
```
/usr/bin/install -c -m 644 ./Misc/python.man \
        /tmp/RtmpKzuaem/R.INSTALL7346f377db9/PythonEmbedInR/inst/share/man/man1/python3.5.1
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
                upgrade) ensurepip="--altinstall --upgrade" ;; \
                install|*) ensurepip="--altinstall" ;; \
        esac; \
         ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Requirement already up-to-date: setuptools in /home/dario.romagnoli/.local/lib/python3.5/site-packages
Requirement already up-to-date: pip in /home/dario.romagnoli/.local/lib/python3.5/site-packages
python version is 3.5.3
```
[...]
```
installing to /usr/local/lib/R/site-library/PythonEmbedInR/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (PythonEmbedInR)
* installing *source* package ‘synapser’ ...
Loading required package: R6
Loading required package: rjson
Loading required package: R6
Loading required package: rjson


Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/RtmpGCWG9G/R.INSTALL3f5063f73b98/synapser/inst/python/installPythonClient.py", line 56, in main

    
stdouterrCapture(lambda: call_pip('pandas', localSitePackages), abbreviateStackTrace=False)
  File "/usr/local/lib/R/site-library/PythonEmbedInR/python/stdouterrCapture.py", line 45, in stdouterrCapture

    
raise exceptionToRaise
  File "/usr/local/lib/R/site-library/PythonEmbedInR/python/stdouterrCapture.py", line 21, in stdouterrCapture

    
return function()
  File "/tmp/RtmpGCWG9G/R.INSTALL3f5063f73b98/synapser/inst/python/installPythonClient.py", line 56, in <lambda>

    
stdouterrCapture(lambda: call_pip('pandas', localSitePackages), abbreviateStackTrace=False)
  File "/tmp/RtmpGCWG9G/R.INSTALL3f5063f73b98/synapser/inst/python/installPythonClient.py", line 105, in call_pip

    
rc = pip.main(['install', packageName,  '--upgrade', '--quiet', '--target', target])
AttributeError
: 
module 'pip' has no attribute 'main'
Error in pyExec(command) : 
  An error has occurred while executing Python code. See traceback above.
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/lib/R/site-library/synapser’

The downloaded source packages are in
        ‘/tmp/Rtmpsuq7As/downloaded_packages’
Warning message:
In install.packages("synapser", repos = c("https://sage-bionetworks.github.io/ran",  :
  installation of package ‘synapser’ had non-zero exit status
```

**Comment by kimyen** [comment]
@romagnolid 
We intended to separate the Python environment within PythonEmbedInR from the user's Python environment. It looks like we failed to do so in your platform:
```
Requirement already up-to-date: setuptools in /home/dario.romagnoli/.local/lib/python3.5/site-packages
Requirement already up-to-date: pip in /home/dario.romagnoli/.local/lib/python3.5/site-packages
```
The above lines are copied from your comment above. These lines indicates that while installing Python for PythonEmbedInR, the installer found `pip` from a different location, where the user's Python packages are. 

Could you also provide the output for the following commands?
```
> library("PythonEmbedInR")
> pyImport("sys")
> pyPrint("sys.path")
```

**Comment by romagnolid** [comment]
Sure
```
['/usr/local/lib/R/site-library/PythonEmbedInR/python', '', '/usr/local/lib/R/site-library/PythonEmbedInR/lib', '/usr/local/lib/R/site-library/PythonEmbedInR/lib/python35.zip', '/usr/local/lib/R/site-library/PythonEmbedInR/lib/python3.5', '/usr/local/lib/R/site-library/PythonEmbedInR/lib/python3.5/plat-linux', '/usr/local/lib/R/site-library/PythonEmbedInR/lib/python3.5/lib-dynload', '/home/dario.romagnoli/.local/lib/python3.5/site-packages', '/usr/local/lib/R/site-library/PythonEmbedInR/lib/python3.5/site-packages', '.']
```

**Comment by kimyen** [comment]
Hi @romagnolid 
It looks like your Python search path `'/home/dario.romagnoli/.local/lib/python3.5/site-packages'` is still included in the PythonEmbedInR environment. 

I open a separate issue to track development work here: https://sagebionetworks.jira.com/browse/SYNR-1298.

**Comment by brucehoff** [comment]
If the problem persists, please contact https://www.synapse.org/#!SynapseForum:default or synapseInfo@sagebase.org.
