### ISSUE TITLE
Configuration fails because module `pip` has no attribute `main`

### ISSUE THREAD

**Issue by attilagk** [Sage-Bionetworks/synapser#268]
## Operating system

Debian GNU/Linux 10 (buster)

## Description of the problem

Where the error occurs:
```
install.packages("synapser", repos=c("https://sage-bionetworks.github.io/ran", "http://cran.fhcrc.org"))    
...
rc = pip.main(['install', packageName, '--upgrade', '--quiet', '--target', target])                                                           
AttributeError
:
module 'pip' has no attribute 'main'
Error in PythonEmbedInR::pyExec(command) :
  An error has occurred while executing Python code. See traceback above.                                                                     
Execution halted
ERROR: configuration failed for package ‘synapser’
```

### Expected behavior

Error-free installation.

### Actual behavior

```
> install.packages("synapser", repos=c("https://sage-bionetworks.github.io/ran", "http://cran.fhcrc.org"))                                    
Installing package into ‘/home/attila/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://sage-bionetworks.github.io/ran/src/contrib/synapser_0.6.54.tar.gz'                                                        
Content type 'application/gzip' length 132790 bytes (129 KB)
==================================================
downloaded 129 KB

* installing *source* package ‘synapser’ ...
Loading required package: R6
Loading required package: rjson
Loading required package: R6
Loading required package: rjson
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/RtmpCrpmKQ/R.INSTALL6a5a2855c492/synapser/inst/python/installPythonClient.py", line 57, in main                                  


call_pip('pandas==0.22', localSitePackages)
  File "/tmp/RtmpCrpmKQ/R.INSTALL6a5a2855c492/synapser/inst/python/installPythonClient.py", line 106, in call_pip                             


rc = pip.main(['install', packageName, '--upgrade', '--quiet', '--target', target])                                                           
AttributeError
:
module 'pip' has no attribute 'main'
Error in PythonEmbedInR::pyExec(command) :
  An error has occurred while executing Python code. See traceback above.                                                                     
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/home/attila/R/library/synapser’

The downloaded source packages are in
        ‘/tmp/Rtmp2dN5YW/downloaded_packages’
Warning message:
In install.packages("synapser", repos = c("https://sage-bionetworks.github.io/ran",  :                                                        
  installation of package ‘synapser’ had non-zero exit status
```
## Output of `sessionInfo()`

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2
```

**Comment by kimyen** [comment]
Hi @attilagk 

Thank you for reporting the problem! 
I noticed that you are using the old ran endpoint. For scalability we have moved our ran to S3. Its endpoint is http://ran.synapse.org/. New version of `synapser` has been deployed exclusive to the new ran endpoint. 

Please let us know:
1. if you found the old endpoint on any of our document. We would like to fix it.
2. If the latest version of `synapser` still have the problem above.

Thank you.

**Comment by attilagk** [comment]
Hi @kimyen 

Thank you for helping me on this.  I could install synapser.  I saw that you already updated the documentation with the new URLs.

**Comment by kimyen** [comment]
Thanks @attilagk for getting back to this and let us know.
