### ISSUE TITLE
can't load the library(synapser)

### ISSUE THREAD

**Issue by biobibibi** [Sage-Bionetworks/synapser#273]
## Operating system

Windows 10

## Description of the problem

I can download the package alright. But when it comes to "library(synapser)", the error occurs.

### Expected behavior

library(synapser)

### Actual behavior
> library(synapser)
Error: package or namespace load failed for ‘synapser’:
 .onLoad failed in loadNamespace() for 'synapser', details:
  call: PythonEmbedInR::pyExec("syn=synapseclient.Synapse(skip_checks=True)")
  error: 
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:/Program Files/R/R-3.6.1/library/synapser\Lib\site-packages\synapseclient-1.9.3-py3.5.egg\synapseclient\client.py", line 215, in __init__
       self.cache = cache.Cache(cache_root_dir)
     File "C:/Program Files/R/R-3.6.1/library/synapser\Lib\site-packages\synapseclient-1.9.3-py3.5.egg\synapseclient\cache.py", line 89, in __init__
       self.cache_root_dir = cache_root_dir
     File "C:/Program Files/R/R-3.6.1/library/synapser\Lib\site-packages\synapseclient-1.9.3-py3.5.egg\synapseclient\cache.py", line 83, in __setattr__
       os.makedirs(value)
     File "os.py", line 231, in makedirs
     File "os.py", line 241, in makedirs
   OSError: [WinError 123] The filename, directory name, or vol

## Output of `sessionInfo()`

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.1        R6_2.4.0              tools_3.6.1           codetools_0.2-16     
[5] pack_0.1-1            PythonEmbedInR_0.3.37

**Comment by tzw2019** [comment]
Hello! I met the same problem like you, have you fixed it?

**Comment by biobibibi** [comment]
> Hello! I met the same problem like you, have you fixed it?

Hi! Unfortunately, I didn't...

**Comment by muschellij2** [comment]
May have to run as admin?

**Comment by brucehoff** [comment]
If the problem persists, please contact https://www.synapse.org/#!SynapseForum:default or synapseInfo@sagebase.org.
